# application config
server:
  port: ${SERVER_PORT:8123}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/activity/query/api}

# spring config
spring:
  application:
    name: ${APPLICATION_NAME:f9bf853171cb57189fd4b67dba9dbf788c35996918b28a27026be25beb2a904c}

  # mongo config
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/ActivityQueryService}
      database: ${MONGODB_DATABASE:ActivityQueryService}

  # rabbitmq config
  rabbitmq:
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:/}
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    ignoreDeclarationException: ${RABBITMQ_IGNORE_DECLARATION_EXCEPTION:true}
    concurrentConsumers: ${RABBITMQ_CONCURRENT_CONSUMERS:3}
    maxConcurrentConsumers: ${RABBITMQ_MAX_CONCURRENT_CONSUMERS:10}
    receiveTimeout: ${RABBITMQ_RECEIVE_TIMEOUT:100000}
